// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // 使用 SQLite 进行快速开发（无需单独数据库服务器）
    // 生产环境请切换回 PostgreSQL
    url: process.env['DATABASE_URL'] || 'file:./prisma/dev.db',
  },
});
